.github/actions/deploy-happy-stack/action.yml

This PR adds an ENV input to the create/update stack action so that we can configure which environment to update.

feat: adding env input to create/update stack

---

.github/workflows/release.yaml

I moved through various version fo release-please to see if that resolved the issue. Version 2 doesn't seem to work anymore based on our changelog and other pinned versions of version 3 don't seem to fix this issue.

fix: going back to version 3

---

.github/actions/deploy-happy-stack/action.yml

Closes [CCIE-190]
[CCIE-190]: https://czi-eng.atlassian.net/browse/CCIE-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add the ability to pass arbitrary tag into deploy-happy-stack action

---

.github/actions/docker-build-push/action.yml

based off this release: https://github.com/chanzuckerberg/github-actions/pull/131

fix: Update pinned ref action in docker-build-push

---

.github/actions/conventional-commits/action.yml

fix: conventional commit regex capture groups

---

.github/actions/install-happy/action.yaml
.github/workflows/install-happy.yaml

First part of https://czi-tech.atlassian.net/browse/CCIE-1022

fix: find correct latest happy version

---

.github/actions/deploy-happy-stack/action.yml

Description:
I'm trying to use a custom docker compose config path with my happy setup. Would like to bring this possibility to the shared GHA

feat: enable optional docker-compose-path argument

---

.github/actions/jira-validate-reference/action.yaml

Updates the job to add a comment with instructions to PRs that fail the check.

feat: comment on PR when jira validation fails

---

.github/actions/install-happy/action.yaml
.github/actions/tf-plan/action.yml
.github/workflows/test-tf-plan.yml
terraform/envs/rdev/comp2/.terraform.lock.hcl
terraform/envs/rdev/comp2/main.tf
terraform/envs/rdev/vpc/.terraform.lock.hcl
terraform/envs/rdev/vpc/main.tf

This PR introduces a new action in the works. I think it needs a few more iterations, but as is we could start experimenting. The workflow would allow us to execute terraform plans and validations bases on PRs. Right now, we have a very tight coupling mechanism between TFE and PRs. It takes a very long time to run all the speculative plans and prevents us from making out of band terraform applies and plans. Generally having terraform workspaces tied to a git SHA is helpful, but for the core infra team it is a clunky workflow. 
This is the first step to changing this workflow. Here is what it would look like:
* All TFE workspaces would stay the same
* We would update the VCS settings to be CLI driven
* All PRs would run this tf-plan action based on the files that have changed
* Plans would …

feat: terraform plan github action

---

.github/actions/deploy-happy-stack/action.yml

Adds a slice option to the happy stack deploy action.

feat: add slice to happy deploy stack action

---

.github/actions/happy-cleanup/action.yml

Adds logging to make it easier to tell what is being deleted by the cleanup jobs

feat: additional logging for happy-cleanup

---

.github/workflows/argus-docker-build.yaml

This PR allows for folks to utilize a different platform for a particular image. If they do, we will pick the correct architecture for them in the matrix to run on so the build is native speeds.

feat: allow image to be built for different platform

---

.github/workflows/argus-docker-build.yaml

We need to be able to update multiple envs values.yaml files in one go so we can support image promotion. eg: https://github.com/chanzuckerberg/core-platform-example-app/pull/25

feat: argus-docker-build update multiple envs

---

.github/actions/argus-builder/docker-build/action.yml
.github/actions/docker-build-push/action.yml
.github/workflows/argus-docker-build.yaml

https://czi.atlassian.net/browse/CCIE-3285

chore: use pull-through cache in docker-builders for qemu

---

.github/actions/conventional-commits/action.yml

https://chanzuckerbergteam.slack.com/archives/C94RQ5SBV/p1729631596612129

test: test pr title

---

.github/workflows/argus-docker-build.yaml

3.6.1 release pr merged https://github.com/chanzuckerberg/github-actions/pull/334

chore: CCIE-3899 use build-prep@3.6.1

---

.github/workflows/argus-docker-build.yaml

tested in https://github.com/chanzuckerberg/core-platform-example-app/actions/runs/13119598823/job/36602171412 via https://github.com/chanzuckerberg/core-platform-example-app/pull/119

feat: CCIE-3899 Add force_update_manifest to argus-docker-build

---

.github/workflows/release.yaml

follows up https://github.com/chanzuckerberg/github-actions/pull/358

fix: CCIE-3947 add checkout step to release.yaml

---

.github/actions/release-please-semvar/README.md
.github/actions/release-please-semvar/action.yml
.github/workflows/release.yaml

wondering if reusable workflow is a better move here but I'm going to merge this to unbreak mainline first

fix: CCIE-3947 pass app token to release-please-semvar

---

.github/actions/release-please-semvar/action.yml

required to support https://github.com/chanzuckerberg/shared-infra/pull/10726/files#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR24

feat: CCIE-3947 add component-in-tag input to release-please-semvar

---

.github/actions/release-please-semvar/action.yml

Tested in https://github.com/chanzuckerberg/argus-example-app/actions/runs/13642394862/job/38134882855
```
To https://github.com/chanzuckerberg/argus-example-app
* [new tag]         fake_package_name-v11 -> fake_package_name-v11
To https://github.com/chanzuckerberg/argus-example-app
* [new tag]         fake_package_name-v11.4 -> fake_package_name-v11.4
``

feat: tag major/minor version to monorepo components

---

.github/actions/release-please-semvar/action.yml

Testing the new major/minor tags

feat: bumps the version on release-please-semvar

---

.github/actions/release-please-semvar/README.md

as seen in https://github.com/chanzuckerberg/shared-infra/pull/10726
to be merged once ^ is merged and proves to work

chore: CCIE-3947 update release-please-semvar readme

---

.github/actions/argus-builder/docker-build/action.yml
.github/workflows/argus-docker-build.yaml

Opt in to container scanning.
* https://github.com/chanzuckerberg/argus-example-app/pull/225

fix: only run container scanning optin

---

.github/workflows/secrets-scanner.yml

reports secrets both as a comment and inline eg https://github.com/chanzuckerberg/github-actions/pull/418/files

chore: CCIE-4562 add secrets scanning

---

.github/workflows/argus-helm-chart-update.yaml

Include app name in PR title and branch name to differentiate between Helm chart upgrades in different apps in the same repo

fix: include app name in PR title and branch name to support monorepos

---

.github/workflows/check_open_source.yml

some repos use LICENSE instead of LICENSE.md  - seems acceptable

fix: CCIE-4853 accept LICENSE file in OSS repos

---

.github/actions/docker-build-push/action.yml

https://czi.atlassian.net/browse/CCIE-5221
Not a real attribute on this action.

fix: hallucination by AI; not my fault

---

.github/actions/docker-build-push/action.yml

fix: add the base ref back in
