chanzuckerberg/github-actions

.github/actions/deploy-happy-stack/action.yml

This PR adds the env flag to the list check so it properly checks the stack in the right environment.

fix: adding env to list check

---

.github/workflows/release.yaml

Reverts chanzuckerberg/github-actions#81. That PR seems to be breaking how tags work and is tagging everything the same thing.

fix: revert "chore: bump google-github-actions/release-please-action from 3.0.0 to 3.2.1"

---

.github/actions/install-happy/action.yaml

We need to be able to run happy via `sudo` in our local dev environments to install `/etc/hosts` overrides. However, when `sudo` is invoked in a github action, it doesn't have access to the updated `$GITHUB_PATH` managed by this action and was unable to find the happy CLI.

feat: Support installing the happy CLI system-wide

---

.github/actions/deploy-happy-stack/action.yml

Background:
The imaging team working on napari-hub wants to deprecate their happy build process and move to using CZI's reusable actions instead. However, the reusable actions currently don't have a way to delete a stack, and we would need to add that functionality to move entirely to using CZI's reusable actions. This change adds additional flexibility for teams managing their stack resources.
Additionally, while testing our changes, we ran into an error where the script wouldn't create a new stack if there was another stack with a name that contained the new stack's name. For example, if we wanted to create a stack called test but we had already made a stack called test-npm, the script would only try to update test because grep had found an occurrence of test in test-npm in the output …

feat: add delete functionality to deploy-happy-stack

---

.github/actions/get-github-ref-names/action.yml
.github/workflows/get-github-ref-names.yml

We are wanting to delete branches, so this will cover that action.
Tested it in our new playground repo: https://github.com/chanzuckerberg/github-actions-playground/runs/7139716330?check_suite_focus=true
I believe these are the expected results. @jakeyheath lmk if this is right! We're wanting to get the branch name of branch that was just deleted right?

feat: (CCIE-308) Adding delete action

---

.github/actions/conventional-commits/action.yml

As of now, our Conventional Commits github actions doesn’t account for PRODSEC Jira tasks. That means the conventional commits check won’t account for branches/PRs generated from our Jira project.

fix: add PRODSEC jira project to conventional commits regex

---

.github/actions/happy-cleanup/README.md
.github/actions/happy-cleanup/action.yml
.release-please-manifest.json
release-please-config.json

This PR introduces a reusable Github Action that happy repos can leverage to automatically clean up their stale stacks. This is particularly helpful in development and rdev environments where these can accumulate over time and be annoying to clean up manually. To best use this action, take advantage of the [Github Actions cronjob](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) feature to run the action on a regular interval and only clean up stacks which have not been updated in a selected period of time.

feat: reusable action to delete happy stacks

---

.github/actions/install-happy/action.yaml
.github/workflows/install-happy.yaml

When choosing the latest happy release we need to check that the asset we want to install has been added by goreleaser. Without this we have seen intermittent failures. re: https://czi-tech.atlassian.net/browse/CCIE-1653
This code uses the following process to choose the happy version to use:
1. Get a list of releases (ordered newest to oldest)
2. Iterate through the releases and when is encountered that has the tag format `v#.#.#` then check for the asset that we need to install
- If the asset is found: use that version
- If the asset is not found: continue to the next-newest version with the correct tag format

fix: ensure happy asset exists when selecting latest release

---

.github/actions/happy-cleanup/action.yml

The command 
```
happy list --aws-profile "" --output json --env $ENV | jq -r --arg date "$date" '.[] | select(.LastUpdated < $date) | .Name'
```
Should return a list of names of happy stacks from the json output. Instead it returns Nulls.
Updating to 
```
happy list --aws-profile "" --output json --env $ENV | jq -r --arg date 2023-08-23T22:08:49+00:00 '.[] | select(.last_updated < $date) | .stack'
```
returns the expected outcome

fix: mismatched syntax for jq command in happy cleanup

---

.github/actions/cache-tf-providers/action.yml
.github/actions/tf-cache-providers/action.yml
.github/actions/tf-plan/action.yml
.github/workflows/test-tf-cache.yml
terraform/accounts/czi-si/.terraform.lock.hcl
terraform/accounts/czi-si/.terraform/terraform.tfstate
terraform/accounts/czi-si/main.tf
terraform/accounts/czi-si/terragrunt.hcl
terraform/envs/rdev/comp2/terragrunt.hcl
terraform/envs/rdev/vpc/terragrunt.hcl

This PR adds a workflow that uses terragrunt to initialize all envs and accounts in a github repo. It stores all the downloaded providers in the Github Cache. This should be leveraged in a cron job that runs on the main branch. After the cache is created with the cron job, all child jobs in branches can restore this cache and never need to download providers again. Here is example output from the terraform init in the example folders:

feat: add caching for tf providers

---

.github/actions/install-happy/action.yaml

Add missing input parameter `version_lock_file`

fix: CCIE-1770: Add inputs.version_lock_file

---

.github/actions/deploy-happy-stack/action.yml

Add `repository` and `github-token` inputs to the happy deploy. Pass these inputs along to the checkout action, so that we can checkout a different repo from the current.
This helps us trigger a deploy to a happy stack, from a different repo

feat: pass along args to allow a happy deploy from a diff repo

---

.github/actions/deploy-happy-stack/action.yml

I believe I'll need this full syntax for my actions to work as per @alexlokshin-czi 's comment [here](https://czi-edu.slack.com/archives/C04NVSCDFR7/p1697744689224679?thread_ts=1697230548.141359&cid=C04NVSCDFR7)
```
happy update STAGING_STACK_NAME --env staging --image-src-env rdev --image-src-stack rdev_STACK_NAME --image-src-role-arn "arn:aws:iam::ACCOUNT:role/<rdev-role>"
```

feat: include image-source-role-arn input for deploy happy

---

.github/actions/retag-happy/action.yml

Fix the happy addtags github action

fix: happy addtags github action

---

.github/actions/deploy-happy-stack/action.yml

If there is a commit above yours and you are re-running an action, this checkout will always checkout the `main` ref which will actually be a different SHA than the one that triggered the action in the first place. If you are re-running an action, we should always use the same SHA that triggered the action. BTW, this is the default behavior of [actions/checkout](https://github.com/actions/checkout), we're just writing it out specifically so that you can overwrite it with a input parameter.

fix!: don't checkout ref every time

---

.github/actions/conventional-commits/action.yml

`deps` is one of the [`release-please` prefixes](
https://github.com/googleapis/release-please#step-1-ensure-releasable-units-are-merged) that triggers a release, and is useful for forcing a release when dependencies are updated (vs. chore).

feat: allow deps for conventional commits

---

.github/workflows/argus-docker-build.yaml

Reverts chanzuckerberg/github-actions#251
We don't want to use the default token because then no jobs run and merging is blocked. The better option is to use the custom token and have the argus docker build job filter based on files changed

fix: Revert "fix: use default token to prevent build cycle"

---

.github/actions/deploy-happy-stack/action.yml

This PR updates the deploy happy stack action to always log in to the global ECR in the core platform prod account. This allows folks to use the global pull through caches for dockerhub in their Dockerfiles when using happy.

feat: always log in to core platform prod ECR

---

.github/workflows/argus-docker-build.yaml

Switch over the default role for the action to use the prod core platform account.

feat: start using the prod core platform account

---

.github/workflows/argus-docker-build.yaml

Adds arguments to allow users to specify the paths that the action should run on. IE, action will only run on commits that have changed files matching the path filters

feat: embed path filtering into Argus builder workflow

---

.github/workflows/argus-docker-build.yaml

Adds support for specifying `build_args` per image that needs to be built. 
Tested with https://github.com/chanzuckerberg/core-platform-example-app/pull/69/files

feat: support build_args in argus docker builder workflow

---

.github/actions/argus-builder/docker-build/action.yml
.github/workflows/argus-docker-build.yaml

This is needed to avoid conflicts in monorepos with the same service name in multiple apps.

feat: scope Argus ECR repo name with working directory

---

.github/actions/argus-builder/docker-build/action.yml
.github/workflows/argus-docker-build.yaml

This is needed to support building Dockerfiles that use private github package registries. Eg: we need to be able to pass the .npmrc to the docker build context for eng-portal to install the happy-api & PEP npm dependencies

feat: Add secret_files arg to Argus docker builder to allow passing files to build context

---

.github/actions/argus-builder/manifest-update/action.yml
.github/actions/get-github-ref-names/action.yml
.github/workflows/argus-docker-build.yaml

The recent update to this builder action to support triggering it from a `pull_request` trigger involved a change to the checkout action that caused some issues. In the image below, the commits from the builder are dependent on how long it takes to build, meaning sometimes a prior build that took longer to build would overwrite a more recent build that had already committed back to the values yaml.
---
---
This issue arose because the checkout action started receiving a `ref` argument that would be set to the branch name in the case of a `push` event, this caused the job to checkout the latest from the branch and then push over whatever was already there. Not supplying the `ref`, or setting it to an empty string, causes the checkout action to fetch at the point that the workflow was …

fix: prevent manifest update after another commit

---

.github/actions/jira-find-marker/action.yaml
.github/actions/jira-validate-reference/action.yaml

eg:
```
projectKeys: CCIE,ONCALL
```

feat: allow multiple projectKeys in jira automations

---

.github/actions/jira-find-marker/action.yaml
.github/actions/jira-validate-reference/action.yaml

We can't support multiple project keys because the Jira Release can only contain issues from the same project it is a part of

chore: roll back mutliple projectKey support

---

.github/actions/argus-builder/docker-build/action.yml
.github/actions/docker-build-push/action.yml

From the docs:
>  Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
>   Default: true
>   clean: ''

chore: add a clean parameter to the checkout

---

.github/actions/happy-cleanup/action.yml

Fix happy-cleanup job in github actions. In the original script, the empty string in the optional argument `--aws-profile ""` is being stripped in `$(echo $list)`, resulting in the following error (since the happy command isn't using the default aws credentials chain)
> Error: unable to initialize the happy client: unable to retrieve aws account id: could not get identity: operation error STS: GetCallerIdentity, get identity: get credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded
ChatGPT suggested to use an array and the `@` symbol to expand the contents of an array in order to preserve any empty spaces/escaping. 
I tried this out in a [test …

fix: bash script in happy-cleanup github action

---

.github/actions/argus-builder/build-prep/action.yml
.github/workflows/argus-docker-build.yaml

Attempts to address https://github.com/chanzuckerberg/argus/issues/655 by running `Update ArgoCD manifests` only if a PR associated with a push has the `stack` label.
Tested via https://github.com/chanzuckerberg/core-platform-example-app/pull/112 which is on 2.X of this action (hence the merge conflicts).
If we like this approach, what should I do? Maybe create 2.16.0 and 3.7.0? Do we care about supporting 2.X apps? It would be simpler to ask those app owners to use 3.X to gain this benefit. Prior to merging I will rebase on latest and test again on an app using 3.X.
Requires application owners to upgrade their argus-docker-build.yaml version target

fix: do not update manifest on PRs without stack label

---

.github/workflows/argus-docker-build.yaml
README.md

BREAKING CHANGE: requires renaming of org level secrets
* Might consider bundling together with other breaking changes (if any) that may arise from making this repo reusable across orgs
* Cannot rename to `GITHUB_HELPER_*` bc the `GITHUB_` prefix is reserved
* I don't think the GH app is checked into IaC right? anyone reading the README will likely have to reach out to our team to figure out app settings/permissions.
* I generated a new PK for the `CZI Github Helper` app and added `GH_ACTIONS_HELPER_APP_ID` & `GH_ACTIONS_HELPER_PK` as new org secrets. we should delete the old ones after this merges.

feat!: CCIE-3896 rename CZI_GITHUB_HELPER_* to GH_ACTIONS_HELPER_*

---

.github/workflows/argus-docker-build.yaml

Considerations:
1. Github workflows apparently do not allow using a list as an input. I want to support the runs-on labels with more than 1 selector so a workaround I found is to pass a JSON string that gets decoded using `fromJSON()`.
2. Github-hosted arm-based runners are not enabled for private repos
3. There is no way to use x64 for both build-prep and x64 matrix img build steps (not sure if there's a use case for this)
tested in https://github.com/chanzuckerberg/core-platform-example-app/pull/112
are there any other workflows that we want to make `runs-on` configurable? `install-happy` and `test-tfe-cache` are using custom runners but not sure if those should be configurable

feat: CCIE-3978 make argus-docker-build runs-on configurable

---

.github/actions/argus-builder/docker-build/action.yml
.github/workflows/argus-docker-build.yaml

core-platform-settings can't be used from the biohub org so these files have been migrated to the argus-artifacts repo

feat: use ECR settings from argus-artifacts repo

---

.github/actions/argus-builder/docker-build/action.yml
.github/actions/container-scanning/action.yml
.github/workflows/argus-docker-build.yaml

Updates container-scanning action to remove old vulnerability report comments when adding a new comment to reduce noise on the PR
Tested in https://github.com/chanzuckerberg/argus/pull/830

feat: remove old vulnerability comments when adding new vulnerability report comment

---

.github/actions/argus-builder/manifest-update/action.yml
.github/workflows/argus-docker-build.yaml

Pulling the docker image for the `mikefarah/yq` step was getting rate limited by docker.io, this change is in tandem with these other PRs where we now install `yq` directly in the runner base image and no longer need to use the dockerized action step to run it:
- https://github.com/chanzuckerberg/gh-self-hosted-runners/pull/35
- https://github.com/chanzuckerberg/gh-self-hosted-runners/pull/36
- https://github.com/chanzuckerberg/gh-self-hosted-runners/pull/37

fix: don't use docker image for yq

---

.github/actions/jira-validate-reference/action.yaml

Use shell syntax to read inputs as  environment variable, which is described as the fix to prevent arbitrary injections in the codescanning result here: https://github.com/chanzuckerberg/github-actions/security/code-scanning/63
https://czi.atlassian.net/browse/CCIE-4242

fix: expression injections in jira-validate-reference

---

.github/actions/helm-lint/action.yml

There are some issues with this flag (https://github.com/helm/helm/issues/12798). With the flag, it wasn't able to properly lint the files. This action works without the flag. It is still able to find incorrect indentations/missing values.

fix: Remove flag from helm lint

---

.github/actions/helm-lint/action.yml

I tested to see if `helm lint` alone would catch yaml errors and it did so I think we can remove this

fix: remove yamllint from helm-lint action

---

.github/actions/argus-builder/docker-build/action.yml
.github/actions/argus-builder/manifest-update/action.yml
.github/actions/deploy-happy-stack/action.yml
.github/actions/happy-cleanup/action.yml
.github/actions/latest-successful-deployment/action.yml
.github/actions/release-please-semvar/action.yml
.github/actions/retag-happy/action.yml
.github/workflows/argus-docker-build.yaml
.github/workflows/conventional_commits_title.yml
.github/workflows/get-github-ref-names.yml
.github/workflows/install-happy.yaml
.github/workflows/jira-release-version.yaml
.github/workflows/test-tf-cache.yml
.github/workflows/test-tf-plan.yml

I did a manual inspection of the files but no guarantees that this won't break something.
If anyone knows of a place where we run privileged git commands other than update manifest, please let me know.
If this PR doesn't end up breaking anything I'll open PRs for other repos using the same approach.

chore: CCIE-3986 use persist-credentials: false in checkout

---

.github/workflows/argus-helm-chart-update.yaml

Needed to test: https://czi.atlassian.net/browse/CCIE-4951
I want to use this in an example app that is only registered in argus staging, thus need to be able to use a different argus base URL

feat: allow specifying a different argus base url for the helmdep-update workflow

---

.github/actions/docker-build-push/action.yml

This reverts commit 09eb2e44cb47517ee9b380d26f37b2f03aa69bf2.
I think what was happening was two cache-from statements were colliding. Sometimes it would pick the release-please and sometimes it would pick your branch. When it picked the release-please one and had a cache miss, some of the layers would get cached further down the line (like in a multi-stage build), but they matched the wrong branch.

fix: use the cache from prod/staging argus builds (#441)

---

.github/actions/docker-build-push/action.yml

Temporary until we figure out why this isn't working.
Error: buildx failed with: ERROR: failed to build: failed to solve: dependency sha256:b83a87cb2a4ad1bdbb8dbdd614b10d079bb9e69fb5f1cce974e87d86d0aa90f6 is not part of the same cache chain

fix: disable docker caching for now

---

.github/actions/argus-builder/docker-build/action.yml
.github/actions/docker-build-push/action.yml
.github/workflows/argus-docker-build.yaml

This PR switches the cache style from inline to registry. Inline caching is good for really simple docker builds and usecases. However, it doesn't work with multistage builds (only the last stage is cached) and it seems to easily conflict with other cache-from layers. Switching to registry cache style allows us to cache all the multi-stage builds of a Dockerfile and in a separate location than the original image. Hopefully this should make our images smaller since they will no longer contain the cache layers.
* https://docs.docker.com/build/cache/backends/registry/
* https://docs.docker.com/build/cache/backends/inline/
* https://github.com/chanzuckerberg/virtual-cells-platform/actions/runs/18024067121/job/51287660835 - test with registry cache (all layers cached when made an update to …

feat: switch cache from inline to registry

---

.github/actions/argus-builder/docker-build/action.yml
.github/actions/docker-build-push/action.yml
.github/workflows/argus-docker-build.yaml

Curious if the bug will return now that we are using registry cache. I have pinned the buildx builder to the latest stable branch and opened a ticket with buildx. The caching error was only happening in the latest version, which apparently is not released yet. Probably safe to not use it and just pin to the latest stable release instead. Also, the registry caching seems to be working better.
* https://github.com/chanzuckerberg/argus-example-app/actions/runs/18176845306/attempts/1?pr=294
* https://github.com/moby/buildkit/issues/6256

feat: add back in the release-please  branches in cache-from
